project:
  type: website

website:
  title: "Portfolio"
  favicon: "My_picture.jpg"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: "#31BAE9"
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Project"
        href: project.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Umarsmuhammed
      - icon: twitter
        href: https://twitter.com/Umarsmuhammed
format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    highlight-style: zenburn

editor: visual

